// index.tsx
'use client'

import type { FileUploadSelectEvent } from 'primereact/fileupload'
import type { JSX } from 'react'
import { useCallback, useState } from 'react'

import type { OutputFormat } from 'nucleify'
import {
  ACCEPTED_EXTENSIONS,
  AdButton,
  AdCard,
  AdFileUpload,
  AdHeading,
  AdSelect,
  convertFileReact,
  DEFAULT_OUTPUT_FORMAT,
  FORMAT_OPTIONS,
  formatBytes,
  normalizeBaseUrl,
} from 'nucleify'

import './_index.scss'

const convertBaseUrl = normalizeBaseUrl(
  process.env.NEXT_PUBLIC_CONVERT_DOCUMENTS_URL ||
    process.env.NUC_CONVERT_DOCUMENTS_URL
)

export function NucDocuments(): JSX.Element {
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [selectedFormat, setSelectedFormat] = useState<OutputFormat>(
    DEFAULT_OUTPUT_FORMAT
  )
  const [isLoading, setIsLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')

  const onFileSelect = useCallback((event: FileUploadSelectEvent): void => {
    setSelectedFile(event.files?.[0] ?? null)
    setErrorMessage('')
    setSuccessMessage('')
  }, [])

  const clearSelection = useCallback((): void => {
    setSelectedFile(null)
    setErrorMessage('')
    setSuccessMessage('')
  }, [])

  const convertFile = useCallback(async (): Promise<void> => {
    await convertFileReact({
      selectedFile,
      selectedFormat,
      convertBaseUrl,
      setIsLoading,
      setErrorMessage,
      setSuccessMessage,
    })
  }, [selectedFile, selectedFormat])

  return (
    <AdCard
      className="settings-card grided-content"
      header={
        <div className="settings-card-header-container">
          <AdHeading tag={4} text="Convert Data" />
        </div>
      }
    >
      <div className="convert-data-content">
        <p className="convert-data-hint">
          Upload one document and choose target format. Converted file downloads
          automatically.
        </p>

        <div className="convert-data-block">
          <span className="convert-data-block-title">1. Upload document</span>
          <div className="convert-data-upload-row">
            <AdFileUpload
              mode="basic"
              name="file"
              chooseLabel="Select file"
              auto={false}
              multiple={false}
              customUpload
              maxFileSize={10485760}
              accept={ACCEPTED_EXTENSIONS}
              className="convert-data-uploader"
              onSelect={onFileSelect}
              onClear={clearSelection}
            />
          </div>

          {selectedFile ? (
            <div className="convert-data-file-meta">
              <span className="convert-data-file-name">
                {selectedFile.name}
              </span>
              <span className="convert-data-file-size">
                {formatBytes(selectedFile.size)}
              </span>
            </div>
          ) : null}
        </div>

        <div className="convert-data-block">
          <label className="convert-data-label" htmlFor="convert-format">
            2. Choose output format
          </label>
          <AdSelect
            adType="main"
            inputId="convert-format"
            value={selectedFormat}
            options={FORMAT_OPTIONS}
            optionLabel="label"
            optionValue="value"
            placeholder="Choose output format"
            className="convert-data-select"
            onChange={(event: { value: OutputFormat }) =>
              setSelectedFormat(event.value)
            }
          />
        </div>

        <div className="convert-data-actions">
          <AdButton
            adType="main"
            disabled={isLoading || !selectedFile}
            label={isLoading ? 'Converting...' : 'Convert file'}
            className="convert-data-convert-btn"
            type="button"
            onClick={() => void convertFile()}
          />

          {selectedFile && !isLoading ? (
            <AdButton
              severity="danger"
              outlined
              label="Clear selected file"
              type="button"
              onClick={clearSelection}
            />
          ) : null}
        </div>

        {errorMessage ? (
          <p className="convert-data-error">{errorMessage}</p>
        ) : null}
        {successMessage ? (
          <p className="convert-data-success">{successMessage}</p>
        ) : null}
      </div>
    </AdCard>
  )
}

// index.vue
<template>
  <ad-card class="settings-card grided-content">
    <template #header>
      <div class="settings-card-header-container">
        <ad-heading :tag="4" text="Convert Data" />
      </div>
    </template>

    <template #content>
      <div class="convert-data-content">
        <p class="convert-data-hint">
          Upload one document and choose target format. Converted file downloads
          automatically.
        </p>

        <div class="convert-data-block">
          <span class="convert-data-block-title">1. Upload document</span>
          <div class="convert-data-upload-row">
            <ad-file-upload
              ad-type="main"
              mode="basic"
              name="file"
              choose-label="Select file"
              :auto="false"
              :multiple="false"
              :custom-upload="true"
              :max-file-size="10485760"
              :accept="ACCEPTED_EXTENSIONS"
              class="convert-data-uploader"
              @select="onFileSelect"
              @clear="clearSelection"
            />
          </div>

          <div v-if="selectedFile" class="convert-data-file-meta">
            <span class="convert-data-file-name">{{ selectedFile.name }}</span>
            <span class="convert-data-file-size"
              >{{ formatBytes(selectedFile.size) }}</span
            >
          </div>
        </div>

        <div class="convert-data-block">
          <label class="convert-data-label" for="convert-format">
            2. Choose output format
          </label>
          <ad-select
            ad-type="main"
            id="convert-format"
            v-model="selectedFormat"
            :options="FORMAT_OPTIONS"
            option-label="label"
            option-value="value"
            placeholder="Choose output format"
            class="convert-data-select"
          />
        </div>

        <div class="convert-data-actions">
          <ad-button
            ad-type="main"
            :disabled="isLoading || !selectedFile"
            :label="isLoading ? 'Converting...' : 'Convert file'"
            class="convert-data-convert-btn"
            @click="convertFile"
          />

          <ad-button
            v-if="selectedFile && !isLoading"
            severity="danger"
            outlined
            label="Clear selected file"
            @click="clearSelection"
          />
        </div>

        <p v-if="errorMessage" class="convert-data-error">{{ errorMessage }}</p>
        <p v-if="successMessage" class="convert-data-success">
          {{ successMessage }}
        </p>
      </div>
    </template>
  </ad-card>
</template>

<script setup lang="ts">
import { useRuntimeConfig } from 'nuxt/app'
import { ref } from 'vue'

import {
  clearSelection as clearSelectionAction,
  convertFile as convertFileAction,
  formatBytes,
  normalizeBaseUrl,
  onFileSelect as onFileSelectAction,
} from 'nucleify'
import {
  ACCEPTED_EXTENSIONS,
  DEFAULT_OUTPUT_FORMAT,
  FORMAT_OPTIONS,
} from 'nucleify'
import type { FileSelectEvent, OutputFormat } from 'nucleify'

const selectedFile = ref<File | null>(null)
const selectedFormat = ref<OutputFormat>(DEFAULT_OUTPUT_FORMAT)
const isLoading = ref(false)
const errorMessage = ref('')
const successMessage = ref('')

const runtimeConfig = useRuntimeConfig()
const convertBaseUrl = normalizeBaseUrl(
  runtimeConfig.public.convertDocumentsUrl
)

function onFileSelect(event: FileSelectEvent): void {
  onFileSelectAction(event, selectedFile, errorMessage, successMessage)
}

function clearSelection(): void {
  clearSelectionAction(selectedFile, errorMessage, successMessage)
}

async function convertFile(): Promise<void> {
  await convertFileAction({
    selectedFile,
    selectedFormat,
    convertBaseUrl,
    isLoading,
    errorMessage,
    successMessage,
  })
}
</script>

<style lang="scss">
@import 'index';
</style>
